Vagrant.configure("2") do |config|

  # make vm loanodealancer
  config.vm.define "lb" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "lb"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "lb"
    node.vm.network "private_network", ip: "192.168.56.105"
    node.vm.provision "shell", path: "setup-lb.sh"
  end

  # make vm web1 
  config.vm.define "web1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "web1"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "web1"
    node.vm.network "private_network", ip: "192.168.56.102"
    node.vm.provision "shell", path: "setup-web1.sh"
  end

  # make vm web2 
  config.vm.define "web2" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "web2"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "web2"
    node.vm.network "private_network", ip: "192.168.56.103"
    node.vm.provision "shell", path: "setup-web2.sh"
  end

  

  # make vm node2
  config.vm.define "node2" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node2"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "node2"
    node.vm.network "private_network", ip: "192.168.56.100"
    node.vm.provision "shell", path: "setup-db2.sh"
  end

  # make vm node3
  config.vm.define "node3" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node3"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "node3"
    node.vm.network "private_network", ip: "192.168.56.101"
    node.vm.provision "shell", path: "setup-db3.sh"
  end

  # make vm node1
  config.vm.define "node1" do |node|
    node.vm.box = "generic/centos7"
    node.vm.box_check_update = false
    node.vm.provider "virtualbox" do |vb|
      vb.name = "node1"                           
      vb.cpus = 1                               
      vb.memory = 512                           
    end                 
    #node.vm.hostname = "node1"
    node.vm.network "private_network", ip: "192.168.56.99"
    node.vm.provision "shell", path: "setup-db1.sh"
  end
  
end